### PR TITLE
initial commit for test branch

### PR DESCRIPTION
**Pull request by adnan-inci**
can you please review my empty class:) ?

### CODE REVIEW

**Comment by melo0712** [comment]
That looks greatt

**Comment by melo0712** [comment]
but has conflicts

**Comment by adnan-inci** [comment]
i know do you have any guess why does it have conflits? i jsut create a new class thats all

**Comment by melo0712** [comment]
before pushing did you pull the changes... most of the time thats the problem... let me add that rule for future conflicts

**Comment by adnan-inci** [comment]
no.I just think the same thing right now.So i am going to delete this request and make again after pulling

**Comment by melo0712** [comment]
but I cannot put that rule yet...for now I will close the pull request..then you will pull everything then create pull request again

**Pull request closed without merging**
